#!/usr/bin/env python3
"""The frozen-rule check, automated (wayfinder ticket e2bot-19).

`AUDIT.md` claims every order is "the mechanical output of the frozen E2 rule".
`RUNBOOK.md` §6 used to back that claim with a human step — re-run the
verification by hand, method written up in the QLD-model repo. This file is
that step, executable.

It drives `signal_engine.compute_signals()` from the committed backtest export
and asserts EXACT equality against the committed reference signals: 4,786
comparable days, zero mismatches. Any edit that moves the rule fails here.

Offline and deterministic by construction — no network, no Alpaca keys, no
`log/` access, stdlib `unittest` only. Run:
    python3 -m unittest discover -s tests -v

Two things this does NOT cover, stated so the check is not oversold:
  - Only the rule, not the pipeline. `fetch_bars()`, the last-completed-session
    bound (e2bot-09) and the staleness guard need network and stay untested.
  - Not every rule constant is constrained by this series. Mutation-tested
    2026-08-12: XQ 0.90->0.91 moves 34 days, VOL_WIN 20->21 moves 51, L_FAST
    20->19 moves 9, FRAC 0.9->0.89 moves 3, L_TREND 200->199 moves 1 — but
    VOLMAX_WIN 60->59 moves ZERO. A change to the 60-day vol-max window would
    pass this check silently.
"""
import os
import sys
import unittest

import pandas as pd

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join(ROOT, "engine"))

import signal_engine  # noqa: E402

DAILY_CSV = os.path.join(ROOT, "reference", "e2_backtest_daily.csv")
SIGNALS_CSV = os.path.join(ROOT, "reference", "e2_reference_signals.csv")

# Pinned shape of the reference series. These are assertions about the frozen
# exports, not about the rule — if they move, someone regenerated a file that
# both CSVs' headers say is NEVER regenerated by automation.
EXPECTED_ROWS = 5056
EXPECTED_COMPARABLE = 4786  # rows where both sides have a signal
EXPECTED_WARMUP_NAN = 270  # leading rows before SMA200/expanding-252 are defined


def _load():
    """The frozen backtest series and the frozen reference signals, aligned.

    Hard-fails (not skips) on a missing file: a test suite that quietly passes
    when the reference is absent is worse than no test at all.
    """
    for path in (DAILY_CSV, SIGNALS_CSV):
        if not os.path.exists(path):
            raise AssertionError(f"reference file missing: {path}")

    daily = pd.read_csv(DAILY_CSV, comment="#")
    daily["Period"] = pd.to_datetime(daily["Period"]).dt.date
    daily = daily.set_index("Period")

    ref = pd.read_csv(SIGNALS_CSV)
    ref["date"] = pd.to_datetime(ref["date"]).dt.date
    ref = ref.set_index("date")

    if not daily.index.equals(ref.index):
        raise AssertionError("reference CSVs are not on the same calendar")
    return daily, ref


class TestFrozenRuleAgainstReference(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        cls.daily, cls.ref = _load()
        # QLD_ret, NOT pct_change(QLD_px). QLD_px is rounded to 4dp in the
        # export, and recomputing returns from it flips 2020-11-19 (a vol > hi
        # boundary) and changes the NaN shape at 2007-07-19 — 1 day in 4,786.
        # The backtest's own return series is what the reference was generated
        # from, so it is the only apples-to-apples input.
        cls.computed = signal_engine.compute_signals(
            cls.daily["QLD_px"], cls.daily["QLD_ret"]
        )["signal_alloc"]

    def test_reference_series_has_not_moved(self):
        self.assertEqual(len(self.daily), EXPECTED_ROWS)
        self.assertEqual(int(self.ref["signal_alloc"].notna().sum()), EXPECTED_COMPARABLE)

    def test_engine_reproduces_every_reference_signal(self):
        """The whole point: 0 mismatches, exact equality, no tolerance."""
        both = pd.DataFrame(
            {"engine": self.computed, "reference": self.ref["signal_alloc"]}
        )
        comparable = both.dropna()
        self.assertEqual(len(comparable), EXPECTED_COMPARABLE)

        mismatches = comparable[comparable["engine"] != comparable["reference"]]
        self.assertEqual(
            len(mismatches),
            0,
            f"the frozen rule moved on {len(mismatches)} day(s): "
            f"{list(mismatches.index)[:10]}",
        )

    def test_warmup_boundary_agrees(self):
        """Where the engine declines to signal must match the reference too.

        Checked separately from the value comparison because dropna() above
        hides it: an engine that emitted NaN everywhere would pass a naive
        value check with zero mismatches.
        """
        engine_nan = self.computed.isna()
        ref_nan = self.ref["signal_alloc"].isna()
        disagreements = engine_nan[engine_nan != ref_nan]
        self.assertEqual(
            len(disagreements),
            0,
            f"warmup boundary differs on {list(disagreements.index)[:10]}",
        )
        self.assertEqual(int(engine_nan.sum()), EXPECTED_WARMUP_NAN)

    def test_only_the_three_legal_allocations_are_emitted(self):
        self.assertEqual(set(self.computed.dropna().unique()), {0.0, 0.5, 1.0})


if __name__ == "__main__":
    unittest.main()
